### get catalog
GET http://localhost:8090/catalog?own=true
Authorization: Bearer {{accessToken}}

### add item
POST http://localhost:8090/catalog/add
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "title"
}

### share item
GET http://localhost:8090/catalog/{{catalogItemId}}/share
Authorization: Bearer {{accessToken}}

### add item from shareSecret
GET http://localhost:8090/catalog/addSecret/{{shareSecret}}
Authorization: Bearer {{accessToken}}